prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix : <http://localhost:3030/IU#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ref: <http://purl.org/vocab/relationship/>
PREFIX ui: <http://www.w3.org/ns/ui#>

###########################################################################
#2016년에쓴 자작곡 이름은?
###########################################################################
SELECT ?songTitle
WHERE {
  ?x :title ?songTitle .
  ?x rdf:type :Song .
  ?x :year 2016 .
  ?x :composedBy ?아이유 .
  ?x :writtenBy ?아이유 .	
}
###########################################################################
#2016년 콘서트 진행한 도시는?
###########################################################################
SELECT ?location
WHERE {
  ?x :year 2016 .
  ?x rdf:type :Concert .
  ?x :location ?location .
  ?x :heldBy ?아이유
}
###########################################################################
#멜론차트에서 매년 아이유의 봄노래는?
###########################################################################
SELECT ?songName
WHERE {
  ?x :title ?songName .
  ?x :won ?streamingCompany .
  ?x :genre ?genre_ .
  filter regex(str(?streamingCompany),'멜론') .
  filter regex(str(?genre_),'봄') .
}
###########################################################################
#2016년도 아이유가 참여한 콘서트는?
###########################################################################
select ?concertName
where{
  ?x :title ?concertName .
  ?x :year 2016 .
  ?x ^:participatesIn ?아이유 .
}
###########################################################################
#꽃갈피둘 앨범에 참여한 가수들은?
###########################################################################
select ?singerName
where{
  ?x :name ?singerName .
  ?x :participatesIn ?Album .
 filter regex(str(?Album),'꽃갈피둘') .
}
###########################################################################
#아이유의 선공개 곡은?
###########################################################################
SELECT ?songName
WHERE {
  ?x :title ?songName .
  ?x :preReleased true .
}
###########################################################################
#2017년도 콘서트를 한 도시는?
###########################################################################
SELECT ?location
WHERE {
  ?x :year 2017 .
  ?x rdf:type :Concert .
  ?x :location ?location .
  ?x :heldBy ?아이유
}
###########################################################################	
#팔레트로 수상한 상 내역은?
###########################################################################
SELECT ?songName ?songAward
WHERE {
  ?x :title ?songName .
  ?x :won ?songAward.
  filter regex(str(?songName),'팔레트') .
}
###########################################################################	
#2017년도에 수상한 상들은?
###########################################################################	
SELECT distinct?songAward
WHERE { 
?x :title ?songAward .
?x :year 2017 .
?x :awardedBy ?companyName .
}
###########################################################################	
#2017년도에 작사한 곡은?
###########################################################################	
SELECT ?songName
WHERE {
  ?x :year 2017 .
  ?x :title ?songName .
  ?x rdf:type :Song .
  ?x :writtenBy ?아이유
}
###########################################################################	
#2017년에 아이유가 참여한 콘서트의 가수는?
###########################################################################	
select ?concertName
where{
  ?x :title ?concertName .
 ?x :year 2017 .
 ?x ^:participatesIn ?아이유 .
}
###########################################################################	
#밤편지 노래로 수상한 상은?
###########################################################################	
select ?songName ?songAward
where{
?x :title ?songName .
?x :won ?songAward .
filter regex(str(?songName),'밤편지')
}
###########################################################################	
#아이유 유튜브뮤직비디오 조회순위는?
###########################################################################	
SELECT ?MVName ?Rank
WHERE {
  ?y :won ?x .
 ?y :rank ?Rank .
  ?y :title ?MVName
  {
    SELECT ?x 
    WHERE {
      ?x rdf:type :Record .
      ?x :awardedBy ?Youtube_StreamingServiceCompany .
    }
  }
}order by ?Rank
###########################################################################	
#유튜브를 통해 공개한 뮤직비디오곡이름은?
###########################################################################	
SELECT ?mvName
WHERE {
  ?x :title ?mvName .
  ?x :partOf ?streamingCompany .
  filter regex(str(?streamingCompany),'Youtube') .
}
###########################################################################	
#나의아저씨OST에서 작사한 곡은?
###########################################################################	
select ?songName
where{
 ?x :title ?songName .
 ?x :writtenBy ?아이유 .
 ?x :isOrignalSoundTrackOf ?나의아저씨_DramaWork .
}

###########################################################################	
#2018년 가온차트뮤직어워드에서 수상한 내역은?
###########################################################################	
SELECT ?awardName ?streamingCompany
WHERE {
  ?x :title ?awardName .
  ?x :year 2018 .
 filter regex(str(?awardName),'가온')
}
###########################################################################	
#2018년에 아이유가 참여한 콘서트의 가수는?
###########################################################################	
select ?concertName
where{
  ?x :title ?concertName .
 ?x :year 2018 .
 ?x ^:participatesIn ?아이유 .
}
###########################################################################	
#선우정아와 관련된 곡은?
###########################################################################	
select ?songName ?origSinger
where{
 ?x :title ?songName .
 ?x :collaborateWith ?아이유 .
 ?x :creates ?origSinger .
 filter regex(str(?origSinger),'선우정아') .
}
###########################################################################	
#지코앨범에 참여한 곡은?
###########################################################################	
select ?songName ?origSinger
where{
  ?x :title ?songName .
?x :collaborateWith ?아이유 .
 ?x :creates ?origSinger .
filter regex(str(?origSinger),'지코') .
}
###########################################################################	
#김동률 앨범에 참여한 곡은?
###########################################################################	
select ?songName ?origSinger
where{
  ?x :title ?songName .
?x :collaborateWith ?아이유 .
 ?x :creates ?origSinger .
filter regex(str(?origSinger),'김동률') .
}