prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix :<http://localhost:3030/IU#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ref: <http://purl.org/vocab/relationship/>
PREFIX ui: <http://www.w3.org/ns/ui#>

###########################################################################
#1.미아가 수록된 앨범은?
###########################################################################
SELECT ?partOf
WHERE {
    ?x :partOf ?partOf .
    ?x rdf:type :Song .
    ?x :title ?"미아" .
}

###########################################################################
#2.아이유의 데뷔곡이 수록된 앨범은?
###########################################################################
SELECT ?y
WHERE {
  ?y rdf:type/rdfs:subClassOf* :MusicAlbum .
  ?y :hasTrackOf ?x .
  {
    SELECT ?x
    WHERE {
     ?x rdf:type :Song .
     ?x :debutSongOf ?아이유 .
    }
  }
}

###########################################################################
#3.로스트 & 파운드 앨범의 프로듀서는?
###########################################################################
SELECT ?result
WHERE {
 ?x :producedBy ?result .
 ?x rdf:type :MiniAlbum .
 ?x :order 1 .
}

###########################################################################
#4.아이유의 데뷔곡은?
###########################################################################
SELECT ?result
WHERE {
 ?x :title ?result .
 ?x rdf:type :Song .
 ?x :debutSongOf ?아이유 .
}

###########################################################################
#5.부가 수록된 앨범제목은?
###########################################################################
SELECT ?result
WHERE {
    ?y :title ?result .
    ?y rdf:type/rdfs:subClassOf* :MusicAlbum .
    ?y :hasTrackOf ?x .
    {
        SELECT ?x
        WHERE {
            ?x rdf:type :Song .
            ?x :title ?"부" .
        }
    }
}

###########################################################################
#6.아이유 1집 Growing Up은 2009년 발매했다.
###########################################################################
SELECT ?result
WHERE {
    ?x :title ?result .
    ?x rdf:type/rdfs:subClassOf* :MusicAlbum .
    ?x :year 2009 .
}

###########################################################################
#7.미니앨범 2집의 총 재생시간은?
###########################################################################
SELECT ?time
WHERE {
 ?x :runningTime ?time .
 ?x rdf:type :MiniAlbum .
 ?x :order 2 .
}

###########################################################################	
#8.마쉬멜로우는 뮤직비디오를 제작했다.
###########################################################################
SELECT ?x
WHERE {
 ?x rdf:type :MusicVideo .
 ?x :expressFor ?마쉬멜로우_Song .
}

###########################################################################	
#9.두번째 미니앨범의 수록곡 장르 목록은?
###########################################################################	
SELECT ?genre
WHERE {
  ?y :genre ?genre .
  ?y :title ?title .
  ?y rdf:type :Song .
  ?y :partOf ?x .
  {
    SELECT ?x
    WHERE {
    ?x rdf:type :MiniAlbum .
    ?x :order 2 .
    }
  }
}
GROUP BY ?genre

###########################################################################	
#10.REAL의 발매일자는?
###########################################################################	
SELECT ?result
WHERE {
    ?x :released ?result .
    ?x rdf:type :MiniAlbum .
    ?x :order 3 .
}

###########################################################################	
#11.서울에서 열린 아이유의 콘서트는?
###########################################################################	
SELECT ?x
WHERE {
 ?x rdf:type :Concert .
 ?x :location ?"서울" .
}

###########################################################################	
#12.나만 몰랐던 이야기가 수록된 앨범 제목은?
###########################################################################	
SELECT ?result
WHERE {
    ?y :title ?result .
    ?y rdf:type/rdfs:subClassOf* :MusicAlbum .
    ?y :hasTrackOf ?x .
    {
        SELECT ?x
        WHERE {
            ?x rdf:type :Song .
            ?x :title ?"나만몰랐던이야기" .
        }
    }
}

###########################################################################	
#13.나만 몰랐던 이야기의 작사, 작곡가 이름은?
###########################################################################	
SELECT ?result1 ?result2
WHERE {
 ?x :writtenBy ?result1 .
 ?x :composedBy ?result2 .
 ?x rdf:type :Song .
 ?x :title ?"나만몰랐던이야기" .
}

###########################################################################	
#14.너랑 나의 작사, 작곡가 이름은?
###########################################################################	
SELECT ?result1 ?result2
WHERE {
 ?x :writtenBy ?result1 .
 ?x :composedBy ?result2 .
 ?x rdf:type :Song .
 ?x :title ?"너랑나" .
}

###########################################################################	
#15.정규 2집의 수록곡 목록은?
###########################################################################	
SELECT ?result
WHERE {
 ?x :hasTrackOf ?result .
 ?x rdf:type :ExtendedPlayAlbum .
 ?x :order ?2 .
}

###########################################################################	
#16.정규 2집의 수록곡은 총 몇곡인가?
###########################################################################	
SELECT ?result
WHERE {
 ?x :numberOfTracks ?result .
 ?x rdf:type :ExtendedPlayAlbum .
 ?x :order 2 .
}

###########################################################################	
#17.두번째 정규앨범 제목은?
###########################################################################	
SELECT ?result
WHERE {
 ?x :title ?result .
 ?x rdf:type :ExtendedPlayAlbum .
 ?x :order 2 .
}

###########################################################################	
#18.너랑 나의 수상 내역은?
###########################################################################	
SELECT ?won
WHERE {
    ?x :won ?won .
    ?x rdf:type :Song .
    ?x :title ?"너랑나" .
}

###########################################################################	
#19. 스무살의 봄 싱글앨범의 총 수록곡 수는?
###########################################################################	
SELECT ?x ?count
WHERE {
  ?x :numberOfTracks ?count .
  ?x rdf:type :SingleAlbum .
}

###########################################################################	
#20.성시경과 콜레보레이션한 가수 이름은?
###########################################################################	
SELECT ?result
WHERE {
 ?x :collaborateWith ?result .
 ?x rdf:type :Singer .
 ?x :name "성시경" .
}